### ISSUE TITLE
签到提示您还未通过图形验证

### ISSUE THREAD

**Issue by AticTI** [raindrop-hb/tencent-video#1]
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/TPwHGZNG/ATv3-JH8-JCWUPUV-F-BQ.png' border='0' alt='ATv3-JH8-JCWUPUV-F-BQ'/></a>

**Comment by raindrop-hb** [comment]
腾讯视频在非官方软件签到会必须验证验证码，现在只能通过app抓cookie了，代码已更新
