### ISSUE TITLE
企业微信收不到通知，是设置错了吗

### ISSUE THREAD

**Issue by oudaiyi** [raindrop-hb/tencent-video#7]
![image](https://github.com/raindrop-hb/tencent-video/assets/96033220/d4384019-577d-4363-882b-3b5c22b17095)

**Comment by raindrop-hb** [comment]
可能是我说错了，更新后的配置文件开关都是用True或False
![image](https://github.com/raindrop-hb/tencent-video/assets/72308008/983c9807-1aee-4994-8d75-2190b21b1985)
